#!/bin/bash

REPO=pretend-mysql-repo/
expr $(cat "$REPO/version") + 1 > "$REPO/version.new"
mv "$REPO/version.new" "$REPO/version"

pushd $REPO
  git config --global user.email "core-services-bot@pivotal.io"
  git config --global user.name "Final Release Builder"

  git add version
  git commit -m "Autoincrement version"
popd
