#!/bin/sh

set -eux

git clone concourse-tests concourse-tests-dirty

echo "Neat, more stuff" >> $OUTPUT_DIR/data/timestamps.txt

cd concourse-tests-dirty

git config --global user.email "autobot@concourse.ci"
git config --global user.name "Concourse"

git add .

git commit -m "Autocommit #2 from Concourse"

