#!/bin/bash

set -eux

CWD=$(pwd)

aws=$(cat "${CWD}/aws-bosh-stemcell/version")
gcp=$(cat "${CWD}/gcp-bosh-stemcell/version")
boshlite=$(cat "${CWD}/bosh-lite-stemcell/version")

if [[ "${aws}" != "${gcp}" || "${aws}" != "${boshlite}" ]]; then
	set +x
	echo "Not all stemcells are on the same version"
	echo "aws=${aws}"
	echo "gcp=${gcp}"
	echo "boshlite=${boshlite}"
	exit 1
fi




